name: Tompang
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12a19a'
    - '#000000'
    - '#00ffff'
    - '#005555'
    - '#0080ff'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
